// This file is auto-generated by `convex dev`.
// If you haven't run `npx convex dev` yet, this stub allows the app to compile.
// Run `npx convex dev` to generate the real version.

export const api = {
  users: {
    createUser: 'users:createUser',
    getUserByEmail: 'users:getUserByEmail',
    getUserById: 'users:getUserById',
    updateUser: 'users:updateUser',
    createSession: 'users:createSession',
    getSession: 'users:getSession',
    deleteSession: 'users:deleteSession',
  },
  library: {
    getLibrary: 'library:getLibrary',
    getLibraryEntry: 'library:getLibraryEntry',
    addToLibrary: 'library:addToLibrary',
    updateProgress: 'library:updateProgress',
    toggleFavourite: 'library:toggleFavourite',
    removeFromLibrary: 'library:removeFromLibrary',
    getChapters: 'library:getChapters',
    getChapter: 'library:getChapter',
    saveChapters: 'library:saveChapters',
  },
} as const
